version: '3.9'

services:
  postgres_db:
    image: 'postgres'
    container_name: postgres_cake_db
    volumes:
      - ./postgres_data:/var/lub/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cake_db
    networks:
      - net
  backend:
    build: .
    container_name: cake-app-backend
    ports:
      - '8080:8080'
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_cake_db:5432/cake_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - net
networks:
  net:
